# Session 1.2 : Pandas for Data Analysis

_Analytics Through Coding Autumn 2026_

---

You have already encountered pandas during the pre-course preparation.  
In this session, we will **refresh the core pandas skills that we need for analysis**, then focus on understanding, checking and selecting data before carrying out any analysis.

The aim is not to memorise every pandas command. Instead, we want to develop a reliable workflow for asking:

* What does this dataset contain?
* Is the data in the form I expect?
* Are there missing or unusual values?
* How can I select the observations I need?
* What simple summaries help me understand the data?

---

## Starting out

First, we import the packages that we will use.

By convention, pandas is imported as `pd` and NumPy as `np`.

In [1]:
import pandas as pd
import numpy as np

## Creating and reading data

A pandas **DataFrame** is a two-dimensional table made up of rows and columns.

We can create one manually, although in practice we will usually read data from a file.

In [2]:
df = pd.read_csv("..\Data\wine_reviews.csv")
df = df.reset_index(drop=True)

df.head()

<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\bacon\AppData\Local\Temp\ipykernel_11948\3480306058.py:1: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  df = pd.read_csv("..\Data\wine_reviews.csv")

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,77718,Australia,"Possibly a little sweet, this is a soft, easyg...",NaN,83,5.0,Australia Other,South Eastern Australia,NaN,Joe Czerwinski,@JoeCz,Banrock Station 2006 Chardonnay (South Eastern...,Chardonnay,Banrock Station
1,67681,France,"A soft, almost off dry wine that is full in th...",Réserve,85,12.0,Rhône Valley,Côtes du Rhône,NaN,Roger Voss,@vossroger,Cellier des Dauphins 2015 Réserve Rosé (Côtes ...,Rosé,Cellier des Dauphins
2,69877,Spain,Generic white-fruit aromas of peach and apple ...,Estate Grown & Bottled,86,9.0,Northern Spain,Rueda,NaN,Michael Schachner,@wineschach,Esperanza 2013 Estate Grown & Bottled Verdejo-...,Verdejo-Viura,Esperanza
3,46544,US,This is the winery's best Nebula in years. Whi...,Nebula,87,29.0,California,Paso Robles,Central Coast,NaN,NaN,Midnight 2010 Nebula Cabernet Sauvignon (Paso ...,Cabernet Sauvignon,Midnight
4,186,US,This is a very rich Pinot whose primary virtue...,Wiley Vineyard,88,40.0,California,Anderson Valley,NaN,NaN,NaN,Harrington 2006 Wiley Vineyard Pinot Noir (And...,Pinot Noir,Harrington

<div class="alert alert-warning">
<b>Refresher.</b>
A DataFrame is similar to a spreadsheet table. Rows normally represent observations and columns represent variables.
</div>

### Exercise

Using the `sales` DataFrame above:

1. Display the column names.
2. Determine the number of rows and columns.
3. Display the data type of each column.

In [3]:
print(df.columns)
print(df.dtypes)

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='str')
Unnamed: 0                 int64
country                      str
description                  str
designation                  str
points                     int64
price                    float64
province                     str
region_1                     str
region_2                     str
taster_name                  str
taster_twitter_handle        str
title                        str
variety                      str
winery                       str
dtype: object

More often, DataFrames are created from data files such as **CSV (comma-separated values)** files using `pd.read_csv()`.

Let's import the wine reviews dataset that we will use throughout this session.

## First look at a dataset

When you receive a new dataset, avoid immediately jumping into analysis.

A good first step is to understand its **shape, structure and variables**.

In [4]:
df.shape

(58487, 14)

In [5]:
df.columns

Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='str')

In [6]:
df.values

array([[77718, 'Australia',
        'Possibly a little sweet, this is a soft, easygoing Chardonnay marked by clean, modest pear and melon flavors.',
        ..., 'Banrock Station 2006 Chardonnay (South Eastern Australia)',
        'Chardonnay', 'Banrock Station'],
       [67681, 'France',
        'A soft, almost off dry wine that is full in the mouth. It has caramel and spice flavors as well as light acidity. The wine feels weighty and definitely needs food.',
        ..., 'Cellier des Dauphins 2015 Réserve Rosé (Côtes du Rhône)',
        'Rosé', 'Cellier des Dauphins'],
       [69877, 'Spain',
        'Generic white-fruit aromas of peach and apple are slightly pithy. This feels good but innocuous, while flavors of apple and stone fruits lose some of their snap and directness on a tropical-tasting finish.',
        ...,
        'Esperanza 2013 Estate Grown & Bottled Verdejo-Viura (Rueda)',
        'Verdejo-Viura', 'Esperanza'],
       ...,
       [96141, 'Italy',
        "Made from Negroamaro, this opens with aromas of red berry, apple and a whiff of wild flower. It's bright and refreshing, offering raspberry notes and a hint of white pepper alongside crisp acidity.",
        ..., 'Masseria Altemura 2016 Rosato (Salento)', 'Rosato',
        'Masseria Altemura'],
       [75013, 'US',
        "This big, bold wine has the taste profile of a Port but is not so sweet or full bodied. Deeper than usual in color, it's concentrated to the point of overripeness in aroma. Rich on the palate with flavors like blackberry syrup and dark chocolate, it should be perfect as an after-dinner wine.",
        ...,
        "Jaxon Keys 2013 Estate Mae's Block Ravazzi Vineyard Zinfandel (Mendocino)",
        'Zinfandel', 'Jaxon Keys'],
       [106613, 'Spain',
        "Zingy and sort of floral on the nose, but fairly pickled, less than pure fruit mars the flavor profile. White wine from La Mancha has never been a Spanish strong suit, and while this wine isn't cloying, sharp or dead on arrival, it doesn't add up to much.",
        ..., 'Finca Antigua 2006 Blanco Viura (La Mancha)', 'Viura',
        'Finca Antigua']], shape=(58487, 14), dtype=object)

### Think about the data

Before continuing, ask yourself:

* What does one row represent?
* What does each column represent?
* Which variables are numerical?
* Which variables are categorical or text?
* Are any data types unexpected?

These questions help us understand what we can reasonably do with the data.

### Exercise

Use pandas to:

1. Display the first 10 rows.
2. Display the last 5 rows.
3. Determine the number of observations and variables.
4. Display the names of all variables.

In [7]:
display(df.head(10))
display(df.tail(5))


print(df.shape[0])

print(df.columns)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,77718,Australia,"Possibly a little sweet, this is a soft, easyg...",NaN,83,5.0,Australia Other,South Eastern Australia,NaN,Joe Czerwinski,@JoeCz,Banrock Station 2006 Chardonnay (South Eastern...,Chardonnay,Banrock Station
1,67681,France,"A soft, almost off dry wine that is full in th...",Réserve,85,12.0,Rhône Valley,Côtes du Rhône,NaN,Roger Voss,@vossroger,Cellier des Dauphins 2015 Réserve Rosé (Côtes ...,Rosé,Cellier des Dauphins
2,69877,Spain,Generic white-fruit aromas of peach and apple ...,Estate Grown & Bottled,86,9.0,Northern Spain,Rueda,NaN,Michael Schachner,@wineschach,Esperanza 2013 Estate Grown & Bottled Verdejo-...,Verdejo-Viura,Esperanza
3,46544,US,This is the winery's best Nebula in years. Whi...,Nebula,87,29.0,California,Paso Robles,Central Coast,NaN,NaN,Midnight 2010 Nebula Cabernet Sauvignon (Paso ...,Cabernet Sauvignon,Midnight
4,186,US,This is a very rich Pinot whose primary virtue...,Wiley Vineyard,88,40.0,California,Anderson Valley,NaN,NaN,NaN,Harrington 2006 Wiley Vineyard Pinot Noir (And...,Pinot Noir,Harrington
5,73126,US,"An unabashedly rich and luscious wine, this co...",NaN,90,22.0,California,Sonoma County-Monterey County-Santa Barbara Co...,California Other,Jim Gordon,@gordone_cellars,Meiomi 2013 Chardonnay (Sonoma County-Monterey...,Chardonnay,Meiomi
6,26800,US,"This opens with a pleasing toasty aroma, follo...",Five Faces,90,33.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Fullerton 2014 Five Faces Pinot Noir (Willamet...,Pinot Noir,Fullerton
7,80832,Italy,"Made with 100% Chardonnay, this creamy sparkle...",Saten,89,35.0,Lombardy,Franciacorta,NaN,Kerin O’Keefe,@kerinokeefe,Lantieri de Paratico NV Saten Chardonnay (Fran...,Chardonnay,Lantieri de Paratico
8,86297,US,"Here's a good, everyday Cab if you're looking ...",NaN,84,10.0,California,Central Coast,Central Coast,NaN,NaN,Cupcake 2005 Cabernet Sauvignon (Central Coast),Cabernet Sauvignon,Cupcake
9,56015,France,"Made from low-yielding, 70-year-old vines, thi...",Clos du Château,92,21.0,Provence,Côtes de Provence,NaN,Roger Voss,@vossroger,Domaine du Clos Gautier 2015 Clos du Château R...,Rosé,Domaine du Clos Gautier

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
58482,43857,US,A solid effort from a dependable winery that u...,Winemaker's Reserve,88,35.0,California,Sonoma County,Sonoma,NaN,NaN,Château Souverain 1996 Winemaker's Reserve Cab...,Cabernet Sauvignon,Château Souverain
58483,87060,Greece,"Crushed thyme, pine resin and lemon start this...",Retsina of Attica,86,9.0,Attica,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Kourtaki NV Retsina of Attica Savatiano (Attica),Savatiano,Kourtaki
58484,96141,Italy,"Made from Negroamaro, this opens with aromas o...",NaN,87,15.0,Southern Italy,Salento,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Altemura 2016 Rosato (Salento),Rosato,Masseria Altemura
58485,75013,US,"This big, bold wine has the taste profile of a...",Estate Mae's Block Ravazzi Vineyard,88,32.0,California,Mendocino,NaN,Jim Gordon,@gordone_cellars,Jaxon Keys 2013 Estate Mae's Block Ravazzi Vin...,Zinfandel,Jaxon Keys
58486,106613,Spain,"Zingy and sort of floral on the nose, but fair...",Blanco,82,10.0,Central Spain,La Mancha,NaN,Michael Schachner,@wineschach,Finca Antigua 2006 Blanco Viura (La Mancha),Viura,Finca Antigua

58487
Index(['Unnamed: 0', 'country', 'description', 'designation', 'points',
       'price', 'province', 'region_1', 'region_2', 'taster_name',
       'taster_twitter_handle', 'title', 'variety', 'winery'],
      dtype='str')

## Selecting Data

Selecting data is one of the most common pandas operations.

We will focus on three common situations:

1. Selecting columns.
2. Selecting rows by position or label.
3. Selecting rows using conditions.

We will practise using the wine reviews DataFrame.

### 1. Selecting columns

A single column can be selected using square brackets.

In [8]:
display(df['country'])

0        Australia
1           France
2            Spain
3               US
4               US
           ...
58482           US
58483       Greece
58484        Italy
58485           US
58486        Spain
Name: country, Length: 58487, dtype: str

Multiple columns can be selected by passing a list of column names.

In [9]:
display(df[['country', 'price', 'points']].head())

     country  price  points
0  Australia    5.0      83
1     France   12.0      85
2      Spain    9.0      86
3         US   29.0      87
4         US   40.0      88

### Exercise

Create a DataFrame called `wine_subset` containing only:

* `country`
* `province`
* `points`
* `price`

Display the first 10 rows.

In [10]:
wine_subset = df[['country', 'province' ,'price', 'points']]

wine_subset.head(10)

     country         province  price  points
0  Australia  Australia Other    5.0      83
1     France     Rhône Valley   12.0      85
2      Spain   Northern Spain    9.0      86
3         US       California   29.0      87
4         US       California   40.0      88
5         US       California   22.0      90
6         US           Oregon   33.0      90
7      Italy         Lombardy   35.0      89
8         US       California   10.0      84
9     France         Provence   21.0      92

### 2. Selecting rows with `loc` and `iloc`

`loc[]` selects using **labels**.

`iloc[]` selects using **positions**.

In [11]:
# Select rows with index labels 10, 750 and 1200
df.loc[[10, 75, 1200]]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
10,78536,US,"Amidst cola and sassafras on the nose, there's...",White Hawk Vineyard,89,38.0,California,Santa Barbara County,Central Coast,Matt Kettmann,@mattkettmann,Deep Sea 2011 White Hawk Vineyard Syrah (Santa...,Syrah,Deep Sea
75,126798,France,"Full bodied and lushly textured, this is a top...",Domaine Grand Veneur,92,49.0,Rhône Valley,Châteauneuf-du-Pape,NaN,Joe Czerwinski,@JoeCz,Alain Jaume et Fils 2006 Domaine Grand Veneur ...,Rhône-style Red Blend,Alain Jaume et Fils
1200,108640,US,Full-bodied in apple and pineapple aromas at f...,Hybrid,81,10.0,California,Lodi,Central Valley,Virginie Boone,@vboone,Peltier 2012 Hybrid Chardonnay (Lodi),Chardonnay,Peltier

In [12]:
# Select the first 5 rows and first 4 columns by position
df.iloc[0:5, 0:4]

,Unnamed: 0,country,description,designation
0,77718,Australia,"Possibly a little sweet, this is a soft, easyg...",NaN
1,67681,France,"A soft, almost off dry wine that is full in th...",Réserve
2,69877,Spain,Generic white-fruit aromas of peach and apple ...,Estate Grown & Bottled
3,46544,US,This is the winery's best Nebula in years. Whi...,Nebula
4,186,US,This is a very rich Pinot whose primary virtue...,Wiley Vineyard

<div class="alert alert-warning">
<b>Remember.</b>
<code>loc</code> works with labels and conditions.  
<code>iloc</code> works with numerical positions.
</div>

### Exercise

Create a sub-DataFrame containing the `country`, `province`, `region_1` and `region_2` columns for rows with index labels `10`, `750` and `1200`.

In [13]:
sub_df = df.loc[
    [10, 750, 1200],
    ['country', 'province', 'region_1', 'region_2']
]

display(sub_df)

     country              province              region_1        region_2
10        US            California  Santa Barbara County   Central Coast
750   France  Languedoc-Roussillon      Vin de Pays d'Oc             NaN
1200      US            California                  Lodi  Central Valley

### 3. Selecting rows using conditions

Boolean conditions allow us to keep only observations that satisfy a rule.

In [14]:
df.loc[df["country"] == "France"]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,67681,France,"A soft, almost off dry wine that is full in th...",Réserve,85,12.0,Rhône Valley,Côtes du Rhône,NaN,Roger Voss,@vossroger,Cellier des Dauphins 2015 Réserve Rosé (Côtes ...,Rosé,Cellier des Dauphins
9,56015,France,"Made from low-yielding, 70-year-old vines, thi...",Clos du Château,92,21.0,Provence,Côtes de Provence,NaN,Roger Voss,@vossroger,Domaine du Clos Gautier 2015 Clos du Château R...,Rosé,Domaine du Clos Gautier
11,41016,France,"This ripe, fruity wine has both freshness and ...",Réserve des Vignerons,86,14.0,Loire Valley,Saumur,NaN,Roger Voss,@vossroger,Cave de Saumur 2014 Réserve des Vignerons (Sa...,Chenin Blanc,Cave de Saumur
12,81019,France,This is a smooth and creamy wine with soft app...,Clos le Vigneau,90,18.0,Loire Valley,Vouvray,NaN,Roger Voss,@vossroger,Château Gaudrelle 2010 Clos le Vigneau (Vouvray),Chenin Blanc,Château Gaudrelle
28,129599,France,"This is pretty pale for a Tavel, with a copper...",NaN,90,24.0,Rhône Valley,Tavel,NaN,Joe Czerwinski,@JoeCz,Prieuré de Montézargues 2014 Tavel,Rosé,Prieuré de Montézargues
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58460,124417,France,"Just hinting at maturity, this rich and stylis...",NaN,90,40.0,Bordeaux,Canon-Fronsac,NaN,Roger Voss,@vossroger,Château Canon 2005 Canon-Fronsac,Bordeaux-style Red Blend,Château Canon
58466,21369,France,This wine is crisp and refreshingly fruity. A ...,NaN,85,16.0,Burgundy,Mâcon-Villages,NaN,Roger Voss,@vossroger,Joseph Drouhin 2016 Mâcon-Villages,Chardonnay,Joseph Drouhin
58467,109686,France,The dry character of this wine is emphasized b...,NaN,85,11.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Cave de Hunawihr 2013 Pinot Gris (Alsace),Pinot Gris,Cave de Hunawihr
58477,50237,France,This wine comes from the stony slopes above th...,Renaissance,93,23.0,Southwest France,Gaillac,NaN,Roger Voss,@vossroger,Domaine Rotier 2015 Renaissance Red (Gaillac),Red Blend,Domaine Rotier
58479,105774,France,"Soft, warm and smoky wine, this has a finely l...",NaN,87,16.0,Bordeaux,Castillon Côtes de Bordeaux,NaN,Roger Voss,@vossroger,Château Moulin de Clotte 2009 Castillon Côtes...,Bordeaux-style Red Blend,Château Moulin de Clotte

We can combine conditions using:

* `&` for **and**
* `|` for **or**

Each condition should be placed inside parentheses.

In [15]:
df.loc[(df['country'] == "France") & (df['points'] > 95)]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
868,89734,France,The wine from this clos or walled vineyard in ...,Clos Lanson,96,196.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Lanson 2006 Clos Lanson Chardonnay (Champagne),Chardonnay,Lanson
1359,89730,France,The heady aromatic scent of fresh tangerine pe...,Clos Saint Landelin Vorbourg Grand Cru,97,50.0,Alsace,Alsace,NaN,Anne Krebiehl MW,@AnneInVino,René Muré 2015 Clos Saint Landelin Vorbourg Gr...,Riesling,René Muré
1703,122948,France,"This is a rich, finely structured wine. It is ...",NaN,97,130.0,Bordeaux,Pomerol,NaN,Roger Voss,@vossroger,Vieux Château Certan 2014 Pomerol,Bordeaux-style Red Blend,Vieux Château Certan
1762,116097,France,97-99 Barrel sample. A wonderfully structured ...,Barrel sample,98,NaN,Bordeaux,Pauillac,NaN,Roger Voss,@vossroger,Château Mouton Rothschild 2009 Barrel sample ...,Bordeaux-style Red Blend,Château Mouton Rothschild
3347,9897,France,The producer held this wine back from release ...,Les Echansons,96,160.0,Champagne,Champagne,NaN,Roger Voss,@vossroger,Mailly Grand Cru 2008 Les Echansons (Champagne),Champagne Blend,Mailly Grand Cru
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55902,1569,France,"An immensely structured wine, packed with dark...",NaN,96,200.0,Bordeaux,Saint-Julien,NaN,Roger Voss,@vossroger,Château Léoville Poyferré 2009 Saint-Julien,Bordeaux-style Red Blend,Château Léoville Poyferré
56374,45009,France,This wine brings out the structure inherent in...,Les Clos Grand Cru,96,73.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Domaine Pinson 2013 Les Clos Grand Cru (Chablis),Chardonnay,Domaine Pinson
56958,113564,France,"A wonderfully complete wine, with all the elem...",NaN,96,2000.0,Burgundy,La Romanée,NaN,Roger Voss,@vossroger,Domaine du Comte Liger-Belair 2005 La Romanée,Pinot Noir,Domaine du Comte Liger-Belair
57167,45005,France,"This wine has weight, richness and an intense ...",Vaudésir Grand Cru,96,62.0,Burgundy,Chablis,NaN,Roger Voss,@vossroger,Domaine Jean-Paul et Benoît Droin 2013 Vaudési...,Chardonnay,Domaine Jean-Paul et Benoît Droin
57771,16106,France,"96–98. Barrel sample. This powerful, impressiv...",Barrel Sample,97,NaN,Bordeaux,Pauillac,NaN,Roger Voss,@vossroger,Château Mouton Rothschild 2012 Barrel Sample ...,Bordeaux-style Red Blend,Château Mouton Rothschild

`.isin()` is useful when we want to match several possible values.

In [16]:
df.loc[df['country'].isin(['France', 'Italy'])]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,67681,France,"A soft, almost off dry wine that is full in th...",Réserve,85,12.0,Rhône Valley,Côtes du Rhône,NaN,Roger Voss,@vossroger,Cellier des Dauphins 2015 Réserve Rosé (Côtes ...,Rosé,Cellier des Dauphins
7,80832,Italy,"Made with 100% Chardonnay, this creamy sparkle...",Saten,89,35.0,Lombardy,Franciacorta,NaN,Kerin O’Keefe,@kerinokeefe,Lantieri de Paratico NV Saten Chardonnay (Fran...,Chardonnay,Lantieri de Paratico
9,56015,France,"Made from low-yielding, 70-year-old vines, thi...",Clos du Château,92,21.0,Provence,Côtes de Provence,NaN,Roger Voss,@vossroger,Domaine du Clos Gautier 2015 Clos du Château R...,Rosé,Domaine du Clos Gautier
11,41016,France,"This ripe, fruity wine has both freshness and ...",Réserve des Vignerons,86,14.0,Loire Valley,Saumur,NaN,Roger Voss,@vossroger,Cave de Saumur 2014 Réserve des Vignerons (Sa...,Chenin Blanc,Cave de Saumur
12,81019,France,This is a smooth and creamy wine with soft app...,Clos le Vigneau,90,18.0,Loire Valley,Vouvray,NaN,Roger Voss,@vossroger,Château Gaudrelle 2010 Clos le Vigneau (Vouvray),Chenin Blanc,Château Gaudrelle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58467,109686,France,The dry character of this wine is emphasized b...,NaN,85,11.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Cave de Hunawihr 2013 Pinot Gris (Alsace),Pinot Gris,Cave de Hunawihr
58477,50237,France,This wine comes from the stony slopes above th...,Renaissance,93,23.0,Southwest France,Gaillac,NaN,Roger Voss,@vossroger,Domaine Rotier 2015 Renaissance Red (Gaillac),Red Blend,Domaine Rotier
58479,105774,France,"Soft, warm and smoky wine, this has a finely l...",NaN,87,16.0,Bordeaux,Castillon Côtes de Bordeaux,NaN,Roger Voss,@vossroger,Château Moulin de Clotte 2009 Castillon Côtes...,Bordeaux-style Red Blend,Château Moulin de Clotte
58481,38963,Italy,"Menthol, eucalyptus, violet, berry, clove and ...",Castelletto,94,50.0,Piedmont,Barolo,NaN,Kerin O’Keefe,@kerinokeefe,Mauro Veglio 2010 Castelletto (Barolo),Nebbiolo,Mauro Veglio
58484,96141,Italy,"Made from Negroamaro, this opens with aromas o...",NaN,87,15.0,Southern Italy,Salento,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Altemura 2016 Rosato (Salento),Rosato,Masseria Altemura

### Exercise

Create a DataFrame called `high_scoring_oceania` containing all wines that:

* have at least **95 points**; and
* come from **Australia or New Zealand**.

Keep only the columns `country`, `province`, `points`, `price` and `title`.

Display the first 10 rows.

In [17]:
high_scoring_oceania = df.loc[(df['points'] >= 95 ) & (df['country'].isin(['Australia', 'New Zealand']))]

display(high_scoring_oceania)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
576,34502,Australia,This prodigious wine showcases Barossa's abili...,The Relic,98,135.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2006 The Relic Shiraz (Barossa Valley),Shiraz,Standish
1959,99330,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2014 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds
10872,122939,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck
11474,122507,New Zealand,"This blend of Cabernet Sauvignon (62.5%), Merl...",SQM Gimblett Gravels Cabernets/Merlot,95,79.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Squawking Magpie 2014 SQM Gimblett Gravels Cab...,Bordeaux-style Red Blend,Squawking Magpie
11762,84815,Australia,The Factor is always one of Torbreck's biggest...,The Factor,95,125.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 The Factor Shiraz (Barossa),Shiraz,Torbreck
14670,77036,Australia,RWT (unromantically derived from “Red Wine Tri...,RWT,96,150.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 RWT Shiraz (Barossa Valley),Shiraz,Penfolds
20753,77044,Australia,The fruit for this offering comes from the Gre...,R Reserve,95,105.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kilikanoon 2009 R Reserve Shiraz (Barossa Valley),Shiraz,Kilikanoon
22515,365,Australia,The Taylor family selected Clare Valley for it...,St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2013 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
25802,39962,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,NaN,NaN,Penfolds 1998 RWT Shiraz (Barossa Valley),Shiraz,Penfolds
27293,77037,Australia,Winemaker Dave Powell is no longer with Torbre...,RunRig,96,225.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2007 RunRig Shiraz-Viognier (Barossa ...,Shiraz-Viognier,Torbreck
38114,87143,Australia,"This is wonderfully complex and aromatic, with...",St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2012 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
40662,56956,Australia,You may have to scour the country to secure so...,Andelmonde,97,95.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2012 Andelmonde Shiraz (Barossa Valley),Shiraz,Standish
40858,356,Australia,"Dusty, firm, powerful: just a few apt descript...",Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill
43682,83357,Australia,A throwback to the monster Shiraz style of old...,Grange,96,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2004 Grange Shiraz (South Australia),Shiraz,Penfolds
46466,14354,Australia,This wine's concentrated dark fruit shows in t...,Old Vine,95,60.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kaesler 2006 Old Vine Shiraz (Barossa Valley),Shiraz,Kaesler
54513,16538,Australia,"Rich, dense and intense, this is a big, muscul...",The Family Tree,95,65.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Lambert 2013 The Family Tree Shiraz (Barossa V...,Shiraz,Lambert
56040,38988,Australia,Penfolds Bin 707 has leapt in quality over the...,Bin 707,95,200.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds
56383,345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
58362,98386,Australia,One of the more approachable of the d'Arenberg...,Little Venice Single Vineyard,95,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 Little Venice Single Vineyard ...,Shiraz,D'Arenberg

## Inspecting Data Quality

Before analysing a dataset, we should check whether the data look reliable.

Useful questions include:

* Are values missing?
* Are there duplicated rows?
* Do numerical values have plausible ranges?
* How many unique values does each variable contain?
* Are the data types appropriate?

These checks do not automatically tell us what to do, but they help us identify potential problems.

In [23]:
# How many missing values are in each column?
df.isna().sum().sort_values(ascending=False)

region_2                 35801
designation              16939
taster_twitter_handle    14111
taster_name              11852
region_1                  9538
price                     4083
province                    28
country                     28
Unnamed: 0                   0
description                  0
points                       0
title                        0
variety                      0
winery                       0
dtype: int64

In [19]:
# What proportion of each column is missing?
(df.isna().mean()/100).sort_values(ascending=False)

region_2                 0.006121
designation              0.002896
taster_twitter_handle    0.002413
taster_name              0.002026
region_1                 0.001631
price                    0.000698
province                 0.000005
country                  0.000005
Unnamed: 0               0.000000
description              0.000000
points                   0.000000
title                    0.000000
variety                  0.000000
winery                   0.000000
dtype: float64

In [25]:
# How many completely duplicated rows are there?
df.duplicated().sum()

np.int64(0)

In [21]:
# How many unique values are in each column?
df.nunique().sort_values(ascending=False)

Unnamed: 0               58487
description              56475
title                    56183
designation              22327
winery                   13064
region_1                  1083
variety                    608
province                   373
price                      320
country                     41
points                      21
taster_name                 19
region_2                    17
taster_twitter_handle       15
dtype: int64

In [22]:
# Quick numerical summary
df.describe()

          Unnamed: 0        points         price
count   58487.000000  58487.000000  54404.000000
mean    65039.713988     88.442440     35.537222
std     37428.040524      3.052034     42.727141
min         0.000000     80.000000      4.000000
25%     32880.500000     86.000000     17.000000
50%     64984.000000     88.000000     25.000000
75%     97507.000000     91.000000     42.000000
max    129969.000000    100.000000   2500.000000

<div class="alert alert-warning">
<b>Important.</b>
Finding missing values does not automatically mean that we should drop them or replace them.

Before changing the data, ask:

<ul>
<li>Why might the value be missing?</li>
<li>How much data would we lose by dropping rows?</li>
<li>Would replacing the value introduce unrealistic information?</li>
<li>Could the missingness itself be informative?</li>
</ul>
</div>

### Exercise

Investigate missing values in the `price` column.

1. Count how many prices are missing.
2. Calculate the percentage of observations with a missing price.
3. Create a DataFrame called `missing_price` containing only rows where price is missing.
4. Display the first five rows.

In [ ]:
print(df['price'].isna().sum())
print((df['price'].isna().mean()*100))

missing_price = df.loc[df['price'].isna()]
display(missing_price.head(5))

4083
6.981038521380819

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
15,20284,Italy,"Baked plum, blue flower, dark spice, vanilla a...",Caleno Oro,88,NaN,Southern Italy,Campania,NaN,Kerin O’Keefe,@kerinokeefe,Nugnes 2009 Caleno Oro Aglianico (Campania),Aglianico,Nugnes
46,118840,Italy,Succulent steak or breaded veal would make goo...,Agricola Centolani,90,NaN,Tuscany,Brunello di Montalcino,NaN,NaN,NaN,Pietranera 2008 Agricola Centolani (Brunello ...,Sangiovese Grosso,Pietranera
72,99544,France,"This serious, ripe offering is packed with red...",Grand Vintage Brut Rosé,93,NaN,Champagne,Champagne,NaN,Roger Voss,@vossroger,Moët & Chandon 2004 Grand Vintage Brut Rosé (...,Champagne Blend,Moët & Chandon
84,127356,France,"88-90 Barrel sample. Finely structured, a wine...",La Chapelle de la Mission Haut-Brion Barrel sa...,89,NaN,Bordeaux,Pessac-Léognan,NaN,Roger Voss,@vossroger,Château La Mission Haut-Brion 2009 La Chapelle...,Bordeaux-style Red Blend,Château La Mission Haut-Brion
95,42529,Italy,This passito dessert wine from the island of L...,NaN,90,NaN,Sicily & Sardinia,Malvasia delle Lipari,NaN,NaN,NaN,Cantine Florio 2008 Malvasia delle Lipari,Malvasia,Cantine Florio

## Summary Functions

Summary functions allow us to quickly describe and understand a dataset.

Common examples include:

* `.mean()`
* `.median()`
* `.min()`
* `.max()`
* `.sum()`
* `.value_counts()`
* `.unique()`
* `.describe()`

In [37]:
df["country"].value_counts(ascending=False)

country
US                        24452
France                     9998
Italy                      8857
Spain                      2991
Portugal                   2620
Chile                      1981
Argentina                  1685
Austria                    1475
Australia                  1040
Germany                     980
New Zealand                 640
South Africa                616
Israel                      218
Greece                      213
Canada                      124
Hungary                      71
Bulgaria                     60
Romania                      52
Turkey                       49
Uruguay                      46
Georgia                      39
Croatia                      38
England                      33
Slovenia                     30
Mexico                       27
Moldova                      24
Brazil                       23
Lebanon                      21
Morocco                      14
Peru                          9
Macedonia                     5
Cyprus                        5
Ukraine                       4
India                         4
Luxembourg                    3
Czech Republic                3
Serbia                        3
Armenia                       2
Switzerland                   2
Egypt                         1
Bosnia and Herzegovina        1
Name: count, dtype: int64

In [38]:
df['price'].median()

np.float64(25.0)

### Exercise

Use pandas to answer the following:

1. What is the highest number of points awarded to a wine?
2. What is the lowest number of points?
3. What is the median wine price?
4. Which five countries have the largest number of reviews?

In [ ]:
print(df['points'].max())
print(df['points'].min())
print("median wine price", df['price'].median())

glorp = df['country'].value_counts(ascending=False)

print(glorp[0:5])

100
80
median wine price 25.0
country
US          24452
France       9998
Italy        8857
Spain        2991
Portugal     2620
Name: count, dtype: int64

## Mini Challenge

You have been asked to take a first look at **highly rated wines**.

Create a DataFrame containing wines with at least **95 points** and investigate it.

Using pandas:

1. Create a DataFrame called `high_rated` containing wines with at least 95 points.
2. Determine how many wines meet this condition.
3. Determine which countries are represented.
4. Check how many of these wines have a missing price.
5. Calculate the mean and median price.
6. Display the 10 most expensive highly rated wines using only:
   * `country`
   * `title`
   * `points`
   * `price`

As you work, think about what else you might want to know before drawing conclusions from this subset.

In [ ]:
high_rated = df.loc[df['points'] >= 95]
condition = (high_rated['designation'].unique())

# high_rated.loc[['country', 'title', 'points', 'price']]

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
38,118066,US,"The blend is mainly Cabernet Sauvignon, with t...",La Joie,96,450.0,California,Sonoma County,Sonoma,NaN,NaN,Verité 2007 La Joie Red (Sonoma County),Bordeaux-style Red Blend,Verité
40,73985,France,"A gorgeously perfumed wine, dominated by the r...",NaN,95,295.0,Bordeaux,Saint-Émilion,NaN,Roger Voss,@vossroger,Le Dôme 2009 Saint-Émilion,Bordeaux-style Red Blend,Le Dôme
139,83367,US,The best of a great flight of single-vineyard ...,Nicholas Vineyard,95,90.0,Oregon,Chehalem Mountains,Willamette Valley,Paul Gregutt,@paulgwine,Adelsheim 2009 Nicholas Vineyard Pinot Noir (C...,Pinot Noir,Adelsheim
176,102818,Austria,"A rich, nutty note hints at hazelnut, with liv...",Heiligenstein Alte Reben Reserve,95,74.0,Kamptal,NaN,NaN,Anne Krebiehl MW,@AnneInVino,Bründlmayer 2014 Heiligenstein Alte Reben Rese...,Riesling,Bründlmayer
179,73980,US,"Soft and ripe enough to drink now, after a dec...",Hirsch Vineyard,95,75.0,California,Sonoma Coast,Sonoma,NaN,NaN,Williams Selyem 2009 Hirsch Vineyard Pinot Noi...,Pinot Noir,Williams Selyem

## All Done!

In this session we refreshed how to:

* read a dataset into pandas;
* inspect its structure;
* select columns and rows;
* filter observations using conditions;
* identify missing values and duplicates;
* calculate simple summary statistics;
* check data quality before analysis.

The important habit is to **understand and validate the data before trying to answer an analytical question**.

In the next part of the course, we will build on these foundations to transform, aggregate, reshape and combine datasets.